name: CI with Keploy API Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  keploy-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend   

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash

    - name: Run Keploy Test Suite
      run: |
        export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
        keploy test-suite --app=9d37d025-32c2-49db-b7c8-c254f36a4aa0 --base-path=https://keploy-assignment-2.onrender.com/ --cloud --debug
